"""Update Resins

Revision ID: 06b1afd4ffd7
Revises: 987d42608d3e
Create Date: 2025-08-12 14:43:18.125528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b1afd4ffd7'
down_revision: Union[str, Sequence[str], None] = '987d42608d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resins', 'serial_number',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resins', 'serial_number',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
