"""Update Casting Patterns

Revision ID: 987d42608d3e
Revises: 998a0595cde2
Create Date: 2025-08-12 14:17:22.287770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987d42608d3e'
down_revision: Union[str, Sequence[str], None] = '998a0595cde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('casting_patterns_serial_number_key'), 'casting_patterns', type_='unique')
    op.create_unique_constraint('uq_casting_pattern_casting_product_id_serial_number', 'casting_patterns', ['casting_product_id', 'serial_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_casting_pattern_casting_product_id_serial_number', 'casting_patterns', type_='unique')
    op.create_unique_constraint(op.f('casting_patterns_serial_number_key'), 'casting_patterns', ['serial_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
