"""
Initial migration

Revision ID: 998a0595cde2
Revises: 
Create Date: 2025-08-12 12:16:58.080004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998a0595cde2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casting_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('primary', 'auxiliary', 'heavy_section', name='castingproducttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('blueprint_number', sa.String(length=255), nullable=False),
    sa.Column('is_casting_manual_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_number'),
    sa.UniqueConstraint('name')
    )
    op.create_table('casting_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('iron_oxides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'name', name='uq_iron_oxide_brand_name')
    )
    op.create_table('mold_core_making_machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('available', 'under_maintenance', 'dismissed', name='assetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'model', name='uq_mold_core_making_machine_brand_model')
    )
    op.create_table('molding_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('pressure_units', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('molding_flasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_number', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('available', 'under_maintenance', 'dismissed', name='assetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_number'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('pattern_plate_frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_number', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('available', 'under_maintenance', 'dismissed', name='assetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_number'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('resins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('mold_core', 'universal', name='resintype'), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'name', name='uq_resin_brand_name')
    )
    op.create_table('triethylamines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'name', name='uq_triethylamine_brand_name')
    )
    op.create_table('casting_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('casting_product_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('available', 'under_maintenance', 'dismissed', name='assetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['casting_product_id'], ['casting_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('mold_core_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('casting_product_id', sa.UUID(), nullable=False),
    sa.Column('model_number', sa.String(length=120), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['casting_product_id'], ['casting_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mold_passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('molding_area_id', sa.Integer(), nullable=False),
    sa.Column('casting_technology_id', sa.Integer(), nullable=False),
    sa.Column('pattern_plate_frame_id', sa.UUID(), nullable=True),
    sa.Column('molding_flask_id', sa.UUID(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('primary_casting_product_name', sa.String(length=255), nullable=True),
    sa.Column('reference_code', sa.String(length=255), nullable=True),
    sa.Column('marking_year', sa.Integer(), nullable=True),
    sa.Column('pressing_pressure', sa.Float(), nullable=True),
    sa.Column('sequence_in_shift', sa.Integer(), nullable=True),
    sa.Column('assembly_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('available', 'used', 'defective', name='consumablestatus'), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['casting_technology_id'], ['casting_technologies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['molding_area_id'], ['molding_areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['molding_flask_id'], ['molding_flasks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pattern_plate_frame_id'], ['pattern_plate_frames.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('molding_area_casting_technologies',
    sa.Column('molding_area_id', sa.Integer(), nullable=False),
    sa.Column('casting_technology_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['casting_technology_id'], ['casting_technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['molding_area_id'], ['molding_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('molding_area_id', 'casting_technology_id')
    )
    op.create_table('molding_flask_areas',
    sa.Column('molding_flask_id', sa.UUID(), nullable=False),
    sa.Column('molding_area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['molding_area_id'], ['molding_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['molding_flask_id'], ['molding_flasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('molding_flask_id', 'molding_area_id')
    )
    op.create_table('molding_sand_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casting_technology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['casting_technology_id'], ['casting_technologies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pattern_plate_frame_molding_areas',
    sa.Column('pattern_plate_frame_id', sa.UUID(), nullable=False),
    sa.Column('molding_area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['molding_area_id'], ['molding_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_plate_frame_id'], ['pattern_plate_frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pattern_plate_frame_id', 'molding_area_id')
    )
    op.create_table('mold_cavities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mold_passport_id', sa.UUID(), nullable=False),
    sa.Column('casting_pattern_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('is_functional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['casting_pattern_id'], ['casting_patterns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mold_passport_id'], ['mold_passports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mold_core_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('molding_sand_type_id', sa.Integer(), nullable=False),
    sa.Column('mold_core_type_id', sa.UUID(), nullable=False),
    sa.Column('mold_core_making_machine_id', sa.UUID(), nullable=False),
    sa.Column('resin_id', sa.UUID(), nullable=False),
    sa.Column('triethylamine_id', sa.UUID(), nullable=False),
    sa.Column('iron_oxide_id', sa.UUID(), nullable=True),
    sa.Column('inventory_box_number', sa.String(length=20), nullable=False),
    sa.Column('sand_temperature', sa.Float(), nullable=False),
    sa.Column('control_mold_core_hardness', sa.Float(), nullable=False),
    sa.Column('manufacturing_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('batch_expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'used', 'defective', name='consumablestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['iron_oxide_id'], ['iron_oxides.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mold_core_making_machine_id'], ['mold_core_making_machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mold_core_type_id'], ['mold_core_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['molding_sand_type_id'], ['molding_sand_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resin_id'], ['resins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['triethylamine_id'], ['triethylamines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mold_passport_data_asc',
    sa.Column('mold_passport_id', sa.UUID(), nullable=False),
    sa.Column('molding_sand_type_id', sa.Integer(), nullable=False),
    sa.Column('resin_id', sa.UUID(), nullable=True),
    sa.Column('mold_hardness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mold_passport_id'], ['mold_passports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['molding_sand_type_id'], ['molding_sand_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resin_id'], ['resins.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mold_passport_id')
    )
    op.create_table('mold_passport_data_gsc',
    sa.Column('mold_passport_id', sa.UUID(), nullable=False),
    sa.Column('molding_sand_type_id', sa.Integer(), nullable=False),
    sa.Column('molding_sand_system', sa.Enum('layered', 'unitary', name='moldingsandsystem'), nullable=False),
    sa.Column('molding_sand_number', sa.String(length=20), nullable=False),
    sa.Column('mold_horizontal_density', sa.Float(), nullable=False),
    sa.Column('mold_vertical_density', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mold_passport_id'], ['mold_passports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['molding_sand_type_id'], ['molding_sand_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mold_passport_id')
    )
    op.create_table('mold_cores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mold_cavity_id', sa.UUID(), nullable=False),
    sa.Column('core_batch_id', sa.UUID(), nullable=False),
    sa.Column('hardness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['core_batch_id'], ['mold_core_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mold_cavity_id'], ['mold_cavities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mold_cores')
    op.drop_table('mold_passport_data_gsc')
    op.drop_table('mold_passport_data_asc')
    op.drop_table('mold_core_batches')
    op.drop_table('mold_cavities')
    op.drop_table('pattern_plate_frame_molding_areas')
    op.drop_table('molding_sand_types')
    op.drop_table('molding_flask_areas')
    op.drop_table('molding_area_casting_technologies')
    op.drop_table('mold_passports')
    op.drop_table('mold_core_types')
    op.drop_table('casting_patterns')
    op.drop_table('triethylamines')
    op.drop_table('resins')
    op.drop_table('pattern_plate_frames')
    op.drop_table('molding_flasks')
    op.drop_table('molding_areas')
    op.drop_table('mold_core_making_machines')
    op.drop_table('iron_oxides')
    op.drop_table('casting_technologies')
    op.drop_table('casting_products')
    # ### end Alembic commands ###
